const furnitureData = [
    {
      itemKey: 1,
      url: "vectors/furniture/bed.svg",
      defaultWidth: "200px",
      defaultHeight: "200px",
      description: "Full Bed",
      category: "Bed",
    },
    {
      itemKey: 2,
      url: "vectors/furniture/desk.svg",
      defaultWidth: "210px",
      defaultHeight: "160px",
      description: "L Desk",
      category: "Desk",
    },
    {
      itemKey: 3,
      url: "vectors/furniture/bedsidetable.svg",
      defaultWidth: "50px",
      defaultHeight: "50px",
      description: "SideTable",
      category: "Table",
    },
    {
      itemKey: 4,
      url: "vectors/furniture/plant.svg",
      defaultWidth: "80px",
      defaultHeight: "80px",
      description: "Fern",
      category: "Plant",
    },
    {
      itemKey: 6,
      url: "vectors/furniture/armchair.svg",
      defaultWidth: "125px",
      defaultHeight: "100px",
      description: "Armchair",
      category: "idk",
    },
    {
      itemKey: 7,
      url: "vectors/furniture/beanbag.svg",
      defaultWidth: "100px",
      defaultHeight: "100px",
      description: "Bean Bag",
      category: "idk",
    },
    {
      itemKey: 8,
      url: "vectors/furniture/carpet.svg",
      defaultWidth: "150px",
      defaultHeight: "250px",
      description: "Carpet",
      category: "idk",
    },
    {
      itemKey: 9,
      url: "vectors/furniture/chair.svg",
      defaultWidth: "115px",
      defaultHeight: "115px",
      description: "Chair",
      category: "idk",
    },
    {
      itemKey: 10,
      url: "vectors/furniture/deskchair.svg",
      defaultWidth: "100px",
      defaultHeight: "120px",
      description: "Chair",
      category: "idk",
    },
    {
      itemKey: 11,
      url: "vectors/furniture/diningtable.svg",
      defaultWidth: "236px",
      defaultHeight: "165px",
      description: "Dining",
      category: "idk",
    },
    {
      itemKey: 12,
      url: "vectors/furniture/lamp.svg",
      defaultWidth: "80px",
      defaultHeight: "80px",
      description: "Lamp",
      category: "idk",
    },
    {
      itemKey: 13,
      url: "vectors/furniture/lcouch.svg",
      defaultWidth: "234px",
      defaultHeight: "161px",
      description: "Couch",
      category: "idk",
    },
    {
      itemKey: 14,
      url: "vectors/furniture/leaf.svg",
      defaultWidth: "80px",
      defaultHeight: "80px",
      description: "Plant",
      category: "idk",
    },
    {
      itemKey: 15,
      url: "vectors/furniture/minifridge.svg",
      defaultWidth: "100px",
      defaultHeight: "100px",
      description: "Fridge",
      category: "idk",
    },
    {
      itemKey: 16,
      url: "vectors/furniture/tvstand.svg",
      defaultWidth: "278px",
      defaultHeight: "69px",
      description: "TV Stand",
      category: "idk",
    },
    {
      itemKey: 17,
      url: "vectors/furniture/twinbed.svg",
      defaultWidth: "200px",
      defaultHeight: "115px",
      description: "Twin",
      category: "idk",
    },
    
  ];

export default furnitureData;