const furnitureData = [
    {
      itemKey: 1,
      url: "vectors/furniture/bed.svg",
      defaultWidth: 80,
      defaultHeight: 80,
      description: "Full Bed",
      category: "Bed",
      type: "furniture",
    },
    {
      itemKey: 2,
      url: "vectors/furniture/desk.svg",
      defaultWidth: 84,
      defaultHeight: 64,
      description: "L Desk",
      category: "Desk",
      type: "furniture",
    },
    {
      itemKey: 3,
      url: "vectors/furniture/bedsidetable.svg",
      defaultWidth: 20,
      defaultHeight: 20,
      description: "SideTable",
      category: "Table",
      type: "furniture",
    },
    {
      itemKey: 4,
      url: "vectors/furniture/plant.svg",
      defaultWidth: 32,
      defaultHeight: 32,
      description: "Fern",
      category: "Plant",
      type: "furniture",
    },
    {
      itemKey: 6,
      url: "vectors/furniture/armchair.svg",
      defaultWidth: 50,
      defaultHeight: 40,
      description: "Armchair",
      category: "idk",
      type: "furniture",
    },
    {
      itemKey: 7,
      url: "vectors/furniture/beanbag.svg",
      defaultWidth: 40,
      defaultHeight: 40,
      description: "Bean Bag",
      category: "idk",
      type: "furniture",
    },
    {
      itemKey: 8,
      url: "vectors/furniture/carpet.svg",
      defaultWidth: 60,
      defaultHeight: 100,
      description: "Carpet",
      category: "idk",
      type: "furniture",
    },
    {
      itemKey: 9,
      url: "vectors/furniture/chair.svg",
      defaultWidth: 46,
      defaultHeight: 46,
      description: "Chair",
      category: "idk",
      type: "furniture",
    },
    {
      itemKey: 10,
      url: "vectors/furniture/deskchair.svg",
      defaultWidth: 40,
      defaultHeight: 48,
      description: "Chair",
      category: "idk",
      type: "furniture",
    },
    {
      itemKey: 11,
      url: "vectors/furniture/diningtable.svg",
      defaultWidth: 94,
      defaultHeight: 66,
      description: "Dining",
      category: "idk",
      type: "furniture",
    },
    {
      itemKey: 12,
      url: "vectors/furniture/lamp.svg",
      defaultWidth: 32,
      defaultHeight: 32,
      description: "Lamp",
      category: "idk",
      type: "furniture",
    },
    {
      itemKey: 13,
      url: "vectors/furniture/lcouch.svg",
      defaultWidth: 94,
      defaultHeight: 65,
      description: "Couch",
      category: "idk",
      type: "furniture",
    },
    {
      itemKey: 14,
      url: "vectors/furniture/leaf.svg",
      defaultWidth: 32,
      defaultHeight: 32,
      description: "Plant",
      category: "idk",
      type: "furniture",
    },
    {
      itemKey: 15,
      url: "vectors/furniture/minifridge.svg",
      defaultWidth: 40,
      defaultHeight: 40,
      description: "Fridge",
      category: "idk",
      type: "furniture",
    },
    {
      itemKey: 16,
      url: "vectors/furniture/tvstand.svg",
      defaultWidth: 111,
      defaultHeight: 28,
      description: "TV Stand",
      category: "idk",
      type: "furniture",
    },
    {
      itemKey: 17,
      url: "vectors/furniture/twinbed.svg",
      defaultWidth: 80,
      defaultHeight: 46,
      description: "Twin",
      category: "idk",
      type: "furniture",
    },
    {
      itemKey: 18,
      url: "vectors/furniture/capybara.png",
      defaultWidth: 72,
      defaultHeight: 56,
      description: "Capybara",
      category: "idk",
      type: "furniture",
    },
    {
      itemKey: 19,
      url: "vectors/furniture/duck.png",
      defaultWidth: 50,
      defaultHeight: 50,
      description: "Duck",
      category: "idk",
      type: "furniture",
    },
    
  ];

export default furnitureData;