const structureData = [
  {
    itemKey: 89,
    url: "vectors/structural/leftdoorrotated.svg",
    defaultWidth: 40,
    defaultHeight: 40,
    description: "Left Door",
    category: "Doors",
    type: "structural"
  },
  {
    itemKey: 90,
    url: "vectors/structural/rightdoorrotated.svg",
    defaultWidth: 40,
    defaultHeight: 40,
    description: "Right Door",
    category: "door",
    type: "structural"
  },
  {
    itemKey: 91,
    url: "vectors/structural/leftopeningdoor.PNG",
    defaultWidth: 20,
    defaultHeight: 40,
    description: "Left Door",
    category: "Doors",
    type: "structural"
  },
  {
    itemKey: 92,
    url: "vectors/structural/rightopeningdoor.PNG",
    defaultWidth: 20,
    defaultHeight: 40,
    description: "Right Door",
    category: "Doors",
    type: "structural"
  },
  {
    itemKey: 93,
    url: "vectors/structural/doubledoors.PNG",
    defaultWidth: 20,
    defaultHeight: 60,
    description: "Double Doors",
    category: "Doors",
    type: "structural"
  },
  {
    itemKey: 94,
    url: "vectors/structural/window.PNG",
    defaultWidth: 4,
    defaultHeight: 40,
    description: "Window",
    category: "window",
    type: "structural"
  },
  {
    itemKey: 95,
    url: "vectors/structural/clearpartition.PNG",
    defaultWidth: 60,
    defaultHeight: 6,
    description: "Clear Partition",
    category: "Partitions",
    type: "structural",
  },
  {
    itemKey: 95,
    url: "vectors/structural/solidpartition.PNG",
    defaultWidth: 60,
    defaultHeight: 6,
    description: "Solid Partition",
    category: "Partitions",
    type: "structural",
  },
  {
    itemKey: 96,
    url: "vectors/structural/staircase.PNG",
    defaultWidth: 48,
    defaultHeight: 120,
    description: "Straight Staircase",
    category: "Staircases",
    type: "structural",
  },
  {
    itemKey: 97,
    url: "vectors/structural/widestaircase.PNG",
    defaultWidth: 60,
    defaultHeight: 80,
    description: "Wide Staircase",
    category: "Staircases",
    type: "structural",
  },
  {
    itemKey: 98,
    url: "vectors/structural/spiralstaircase.PNG",
    defaultWidth: 48,
    defaultHeight: 48,
    description: "Spiral Staircase",
    category: "Staircases",
    type: "structural",
  },
  {
    itemKey: 99,
    url: "vectors/structural/lstaircase.PNG",
    defaultWidth: 50,
    defaultHeight: 120,
    description: "L Staircase",
    category: "Staircases",
    type: "structural",
  },
  {
    itemKey: 100,
    url: "vectors/structural/fannedstaircase.PNG",
    defaultWidth: 120,
    defaultHeight: 48,
    description: "Straight Staircase",
    category: "Staircases",
    type: "structural",
  },
  {
    itemKey: 101,
    url: "vectors/structural/pillar.PNG",
    defaultWidth: 24,
    defaultHeight: 24,
    description: "Pillar",
    category: "Pillars",
    type: "structural",
  },
];

export default structureData;