const furnitureData = [
  {
    itemKey: 1,
    url: "vectors/furniture/greyqueenbed.PNG",
    defaultWidth: 60,
    defaultHeight: 80,
    description: "Queen Bed",
    category: "Beds",
    type: "furniture",
  },
  {
    itemKey: 2,
    url: "vectors/furniture/queenbedplussheets.PNG",
    defaultWidth: 60,
    defaultHeight: 80,
    description: "Queen Bed",
    category: "Beds",
    type: "furniture",
  },
  {
    itemKey: 3,
    url: "vectors/furniture/doublebed.PNG",
    defaultWidth: 38,
    defaultHeight: 75,
    description: "Twin Bed",
    category: "Beds",
    type: "furniture",
  },
  {
    itemKey: 4,
    url: "vectors/furniture/singlebed.PNG",
    defaultWidth: 30,
    defaultHeight: 75,
    description: "Single Bed",
    category: "Beds",
    type: "furniture",
  },
  {
    itemKey: 5,
    url: "vectors/furniture/crib.PNG",
    defaultWidth: 28,
    defaultHeight: 52,
    description: "Crib",
    category: "Beds",
    type: "furniture",
  },
  {
    itemKey: 6,
    url: "vectors/furniture/largedresser.PNG",
    defaultWidth: 60,
    defaultHeight: 20,
    description: "Large Dresser",
    category: "Dressers",
    type: "furniture",
  },
  {
    itemKey: 7,
    url: "vectors/furniture/mediumdresser.PNG",
    defaultWidth: 50,
    defaultHeight: 20,
    description: "Medium Dresser",
    category: "Dressers",
    type: "furniture",
  },
  {
    itemKey: 8,
    url: "vectors/furniture/rectangularbrownnightstand.PNG",
    defaultWidth: 30,
    defaultHeight: 20,
    description: "Nightstand",
    category: "Nightstands",
    type: "furniture",
  },
  {
    itemKey: 9,
    url: "vectors/furniture/rectangularwhitenightstand.PNG",
    defaultWidth: 20,
    defaultHeight: 30,
    description: "Nightstand",
    category: "Nightstands",
    type: "furniture",
  },
  {
    itemKey: 10,
    url: "vectors/furniture/squareblacknightstand.PNG",
    defaultWidth: 25,
    defaultHeight: 25,
    description: "Nightstand",
    category: "Nightstands",
    type: "furniture",
  },
  {
    itemKey: 11,
    url: "vectors/furniture/squarebrownnightstand.PNG",
    defaultWidth: 30,
    defaultHeight: 20,
    description: "Nightstand",
    category: "Nightstands",
    type: "furniture",
  },
  {
    itemKey: 12,
    url: "vectors/furniture/squarewhitenightstand.PNG",
    defaultWidth: 30,
    defaultHeight: 20,
    description: "Nightstand",
    category: "Nightstands",
    type: "furniture",
  },
  {
    itemKey: 13,
    url: "vectors/furniture/cornershelves.PNG",
    defaultWidth: 24,
    defaultHeight: 24,
    description: "Corner Shelves",
    category: "Shelves",
    type: "furniture",
  },
  {
    itemKey: 14,
    url: "vectors/furniture/cubbyshelf.PNG",
    defaultWidth: 36,
    defaultHeight: 20,
    description: "Cubby Shelf",
    category: "Shelves",
    type: "furniture",
  },
  {
    itemKey: 15,
    url: "vectors/furniture/floorshelves.PNG",
    defaultWidth: 36,
    defaultHeight: 18,
    description: "Floor Shelves",
    category: "Shelves",
    type: "furniture",
  },
  {
    itemKey: 16,
    url: "vectors/furniture/largeblackshelves.PNG",
    defaultWidth: 60,
    defaultHeight: 20,
    description: "Large Black Shelves",
    category: "Shelves",
    type: "furniture",
  },
  {
    itemKey: 17,
    url: "vectors/furniture/largebrownshelves.PNG",
    defaultWidth: 60,
    defaultHeight: 20,
    description: "Large Brown Shelves",
    category: "Shelves",
    type: "furniture",
  },
  {
    itemKey: 18,
    url: "vectors/furniture/mediumblackshelves.PNG",
    defaultWidth: 50,
    defaultHeight: 20,
    description: "Medium Black Shelves",
    category: "Shelves",
    type: "furniture",
  },
  {
    itemKey: 19,
    url: "vectors/furniture/shelfwithpictures.PNG",
    defaultWidth: 60,
    defaultHeight: 20,
    description: "Decorated Shelf",
    category: "Shelves",
    type: "furniture",
  },
  {
    itemKey: 20,
    url: "vectors/furniture/wireshelves.PNG",
    defaultWidth: 36,
    defaultHeight: 20,
    description: "Wire Shelves",
    category: "Shelves",
    type: "furniture",
  },
  {
    itemKey: 21,
    url: "vectors/furniture/browntvstand.PNG",
    defaultWidth: 60,
    defaultHeight: 18,
    description: "Brown TV Stand",
    category: "TV Stands",
    type: "furniture",
  },
  {
    itemKey: 22,
    url: "vectors/furniture/greytvstand.PNG",
    defaultWidth: 50,
    defaultHeight: 18,
    description: "Grey TV Stand",
    category: "TV Stands",
    type: "furniture",
  },
  {
    itemKey: 23,
    url: "vectors/furniture/smalltvstand.PNG",
    defaultWidth: 36,
    defaultHeight: 18,
    description: "Small TV Stand",
    category: "TV Stands",
    type: "furniture",
  },
  {
    itemKey: 24,
    url: "vectors/furniture/yellowtvstand.PNG",
    defaultWidth: 50,
    defaultHeight: 18,
    description: "Yellow TV Stand",
    category: "TV Stands",
    type: "furniture",
  },
  {
    itemKey: 25,
    url: "vectors/furniture/brownvanity.PNG",
    defaultWidth: 50,
    defaultHeight: 18,
    description: "Brown Vanity",
    category: "Vanities",
    type: "furniture",
  },
  {
    itemKey: 26,
    url: "vectors/furniture/whitevanity.PNG",
    defaultWidth: 50,
    defaultHeight: 18,
    description: "White Vanity",
    category: "Vanities",
    type: "furniture",
  },
  {
    itemKey: 27,
    url: "vectors/furniture/blackwardrobe.PNG",
    defaultWidth: 40,
    defaultHeight: 20,
    description: "Black Wardrobe",
    category: "Wardrobes",
    type: "furniture",
  },
  {
    itemKey: 28,
    url: "vectors/furniture/brownwardrobe.PNG",
    defaultWidth: 40,
    defaultHeight: 20,
    description: "Brown Wardrobe",
    category: "Wardrobes",
    type: "furniture",
  },
  {
    itemKey: 29,
    url: "vectors/furniture/smallblackwardrobe.PNG",
    defaultWidth: 30,
    defaultHeight: 20,
    description: "Small Black Wardrobe",
    category: "Wardrobes",
    type: "furniture",
  },
  {
    itemKey: 30,
    url: "vectors/furniture/smallbrownwardrobe.PNG",
    defaultWidth: 30,
    defaultHeight: 20,
    description: "Small Brown Wardrobe",
    category: "Wardrobes",
    type: "furniture",
  },
  {
    itemKey: 31,
    url: "vectors/furniture/blackchair.PNG",
    defaultWidth: 30,
    defaultHeight: 30,
    description: "Black Chair",
    category: "Chairs",
    type: "furniture",
  },
  {
    itemKey: 32,
    url: "vectors/furniture/blackstool.PNG",
    defaultWidth: 25,
    defaultHeight: 25,
    description: "Black Stool",
    category: "Chairs",
    type: "furniture",
  },
  {
    itemKey: 33,
    url: "vectors/furniture/paddedchair.PNG",
    defaultWidth: 30,
    defaultHeight: 30,
    description: "Padded Chair",
    category: "Chairs",
    type: "furniture",
  },
  {
    itemKey: 34,
    url: "vectors/furniture/whitechair.PNG",
    defaultWidth: 30,
    defaultHeight: 30,
    description: "White Chair",
    category: "Chairs",
    type: "furniture",
  },
  {
    itemKey: 35,
    url: "vectors/furniture/blackdesk.PNG",
    defaultWidth: 60,
    defaultHeight: 30,
    description: "Black Desk",
    category: "Desks",
    type: "furniture",
  },
  {
    itemKey: 36,
    url: "vectors/furniture/browndesk.PNG",
    defaultWidth: 60,
    defaultHeight: 30,
    description: "Brown Desk",
    category: "Desks",
    type: "furniture",
  },
  {
    itemKey: 37,
    url: "vectors/furniture/officechair1.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Officechair 1",
    category: "Chairs",
    type: "furniture",
  },
  {
    itemKey: 38,
    url: "vectors/furniture/officechair2.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Officechair 2",
    category: "Chairs",
    type: "furniture",
  },
  {
    itemKey: 39,
    url: "vectors/furniture/officechair3.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Officechair 3",
    category: "Chairs",
    type: "furniture",
  },
  {
    itemKey: 40,
    url: "vectors/furniture/officechair4.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Officechair 4",
    category: "Chairs",
    type: "furniture",
  },
  {
    itemKey: 41,
    url: "vectors/furniture/officechair5.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Officechair 5",
    category: "Chairs",
    type: "furniture",
  },
  {
    itemKey: 42,
    url: "vectors/furniture/glasstable.PNG",
    defaultWidth: 50,
    defaultHeight: 25,
    description: "Glass Table",
    category: "Tables",
    type: "furniture",
  },
  {
    itemKey: 43,
    url: "vectors/furniture/ovaltable.PNG",
    defaultWidth: 60,
    defaultHeight: 30,
    description: "Oval Table",
    category: "Tables",
    type: "furniture",
  },
  {
    itemKey: 44,
    url: "vectors/furniture/roundtable.PNG",
    defaultWidth: 50,
    defaultHeight: 50,
    description: "Round Table",
    category: "Tables",
    type: "furniture",
  },
  {
    itemKey: 45,
    url: "vectors/furniture/tablewithchairs.PNG",
    defaultWidth: 70,
    defaultHeight: 40,
    description: "Dining Table",
    category: "Tables",
    type: "furniture",
  },
  {
    itemKey: 46,
    url: "vectors/furniture/whitetable.PNG",
    defaultWidth: 50,
    defaultHeight: 30,
    description: "White Table",
    category: "Tables",
    type: "furniture",
  },
  {
    itemKey: 47,
    url: "vectors/furniture/greyarmchair.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Grey Armchair",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 48,
    url: "vectors/furniture/largebluearmchair.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Blue Armchair",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 49,
    url: "vectors/furniture/mediumgreyarmchair.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Rounded Grey Armchair",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 50,
    url: "vectors/furniture/roundarmchair.PNG",
    defaultWidth: 35,
    defaultHeight: 30,
    description: "Round Armchair",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 51,
    url: "vectors/furniture/tallarmchair.PNG",
    defaultWidth: 40,
    defaultHeight: 35,
    description: "Tall Armchair",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 52,
    url: "vectors/furniture/greysquareottoman.PNG",
    defaultWidth: 35,
    defaultHeight: 20,
    description: "Grey Ottoman",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 53,
    url: "vectors/furniture/leggedottoman.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Legged Ottoman",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 54,
    url: "vectors/furniture/roundottoman.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Round Ottoman",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 55,
    url: "vectors/furniture/yellowsquareottoman.PNG",
    defaultWidth: 35,
    defaultHeight: 20,
    description: "Yellow Ottoman",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 56,
    url: "vectors/furniture/blacksofa.PNG",
    defaultWidth: 70,
    defaultHeight: 25,
    description: "Black Sofa",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 57,
    url: "vectors/furniture/greensofa.PNG",
    defaultWidth: 70,
    defaultHeight: 25,
    description: "Green Sofa",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 58,
    url: "vectors/furniture/Lsofa.PNG",
    defaultWidth: 110,
    defaultHeight: 50,
    description: "Corner Sofa",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 59,
    url: "vectors/furniture/reclinersofa.PNG",
    defaultWidth: 110,
    defaultHeight: 80,
    description: "Recliner Sofa",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 60,
    url: "vectors/furniture/roundedsofa.PNG",
    defaultWidth: 70,
    defaultHeight: 25,
    description: "Rounded Sofa",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 61,
    url: "vectors/furniture/Usofa.PNG",
    defaultWidth: 120,
    defaultHeight: 60,
    description: "U Sofa",
    category: "Sofas",
    type: "furniture",
  },
  {
    itemKey: 62,
    url: "vectors/furniture/bedsidelamp.PNG",
    defaultWidth: 15,
    defaultHeight: 15,
    description: "Square Lamp",
    category: "Lighting",
    type: "furniture",
  },
  {
    itemKey: 63,
    url: "vectors/furniture/desklamp.PNG",
    defaultWidth: 15,
    defaultHeight: 24,
    description: "Desk Lamp",
    category: "Lighting",
    type: "furniture",
  },
  {
    itemKey: 64,
    url: "vectors/furniture/floorlamp.PNG",
    defaultWidth: 25,
    defaultHeight: 25,
    description: "Floor Lamp",
    category: "Lighting",
    type: "furniture",
  },
  {
    itemKey: 65,
    url: "vectors/furniture/roundbedsidelamp.PNG",
    defaultWidth: 15,
    defaultHeight: 15,
    description: "Round Lamp",
    category: "Lighting",
    type: "furniture",
  },
  {
    itemKey: 66,
    url: "vectors/furniture/walllamp.PNG",
    defaultWidth: 15,
    defaultHeight: 24,
    description: "Wall Lamp",
    category: "Lighting",
    type: "furniture",
  },
  {
    itemKey: 67,
    url: "vectors/furniture/rug.PNG",
    defaultWidth: 100,
    defaultHeight: 60,
    description: "Rug",
    category: "Accents",
    type: "furniture",
  },
  {
    itemKey: 68,
    url: "vectors/furniture/roses.PNG",
    defaultWidth: 12,
    defaultHeight: 12,
    description: "Roses",
    category: "Accents",
    type: "furniture",
  },
  {
    itemKey: 69,
    url: "vectors/furniture/flowers.PNG",
    defaultWidth: 12,
    defaultHeight: 12,
    description: "Flowers",
    category: "Accents",
    type: "furniture",
  },
  {
    itemKey: 70,
    url: "vectors/furniture/plant.PNG",
    defaultWidth: 12,
    defaultHeight: 12,
    description: "Fern",
    category: "Accents",
    type: "furniture",
  },
  {
    itemKey: 71,
    url: "vectors/furniture/books.PNG",
    defaultWidth: 12,
    defaultHeight: 6,
    description: "Books",
    category: "Accents",
    type: "furniture",
  },
  {
    itemKey: 72,
    url: "vectors/furniture/airconditioner.PNG",
    defaultWidth: 48,
    defaultHeight: 6,
    description: "Air Conditioner",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 73,
    url: "vectors/furniture/bicycle.PNG",
    defaultWidth: 18,
    defaultHeight: 60,
    description: "Bicycle",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 74,
    url: "vectors/furniture/exercisebike.PNG",
    defaultWidth: 24,
    defaultHeight: 60,
    description: "Exercise Bike",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 75,
    url: "vectors/furniture/fan.PNG",
    defaultWidth: 18,
    defaultHeight: 6,
    description: "Fan",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 76,
    url: "vectors/furniture/fridge.PNG",
    defaultWidth: 36,
    defaultHeight: 36,
    description: "Fridge",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 77,
    url: "vectors/furniture/ironingboard.PNG",
    defaultWidth: 48,
    defaultHeight: 12,
    description: "Ironing Board",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 78,
    url: "vectors/furniture/keyboard.PNG",
    defaultWidth: 36,
    defaultHeight: 18,
    description: "Keyboard",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 79,
    url: "vectors/furniture/largetv.PNG",
    defaultWidth: 60,
    defaultHeight: 6,
    description: "Large TV",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 80,
    url: "vectors/furniture/mediumtv.PNG",
    defaultWidth: 36,
    defaultHeight: 6,
    description: "TV",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 81,
    url: "vectors/furniture/smalltv.PNG",
    defaultWidth: 24,
    defaultHeight: 6,
    description: "Small TV",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 82,
    url: "vectors/furniture/piano.PNG",
    defaultWidth: 40,
    defaultHeight: 15,
    description: "Piano",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 83,
    url: "vectors/furniture/projector.PNG",
    defaultWidth: 18,
    defaultHeight: 18,
    description: "Projector",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 84,
    url: "vectors/furniture/pc.PNG",
    defaultWidth: 24,
    defaultHeight: 18,
    description: "Computer",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 85,
    url: "vectors/furniture/speakerset.PNG",
    defaultWidth: 24,
    defaultHeight: 10,
    description: "Speakers",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 86,
    url: "vectors/furniture/washingmachine.PNG",
    defaultWidth: 30,
    defaultHeight: 30,
    description: "Washing Machine",
    category: "Appliances",
    type: "furniture",
  },
  {
    itemKey: 87,
    url: "vectors/furniture/capybara.png",
    defaultWidth: 15,
    defaultHeight: 15,
    description: "Capybara",
    category: "Capybara",
    type: "furniture",
  },
  {
    itemKey: 88,
    url: "vectors/furniture/duck.png",
    defaultWidth: 15,
    defaultHeight: 15,
    description: "Duck",
    category: "Duck",
    type: "furniture",
  },
  
];

export default furnitureData;