const furnitureData = [
  {
    itemKey: 1,
    url: "vectors/furniture/greyqueenbed.PNG",
    defaultWidth: 60,
    defaultHeight: 80,
    description: "Queen Bed",
    category: "Bed",
    type: "furniture",
  },
  {
    itemKey: 2,
    url: "vectors/furniture/queenbedplussheets.PNG",
    defaultWidth: 60,
    defaultHeight: 80,
    description: "Queen Bed",
    category: "Bed",
    type: "furniture",
  },
  {
    itemKey: 3,
    url: "vectors/furniture/doublebed.PNG",
    defaultWidth: 38,
    defaultHeight: 75,
    description: "Twin Bed",
    category: "Twin Bed",
    type: "furniture",
  },
  {
    itemKey: 4,
    url: "vectors/furniture/singlebed.PNG",
    defaultWidth: 30,
    defaultHeight: 75,
    description: "Single Bed",
    category: "Single Bed",
    type: "furniture",
  },
  {
    itemKey: 5,
    url: "vectors/furniture/crib.PNG",
    defaultWidth: 28,
    defaultHeight: 52,
    description: "Crib",
    category: "Crib",
    type: "furniture",
  },
  {
    itemKey: 6,
    url: "vectors/furniture/largedresser.PNG",
    defaultWidth: 60,
    defaultHeight: 20,
    description: "Large Dresser",
    category: "Large Dresser",
    type: "furniture",
  },
  {
    itemKey: 7,
    url: "vectors/furniture/mediumdresser.PNG",
    defaultWidth: 50,
    defaultHeight: 20,
    description: "Medium Dresser",
    category: "Medium Dresser",
    type: "furniture",
  },
  {
    itemKey: 8,
    url: "vectors/furniture/rectangularbrownnightstand.PNG",
    defaultWidth: 30,
    defaultHeight: 20,
    description: "Nightstand",
    category: "Nightstand",
    type: "furniture",
  },
  {
    itemKey: 9,
    url: "vectors/furniture/rectangularwhitenightstand.PNG",
    defaultWidth: 20,
    defaultHeight: 30,
    description: "Nightstand",
    category: "Nightstand",
    type: "furniture",
  },
  {
    itemKey: 10,
    url: "vectors/furniture/squareblacknightstand.PNG",
    defaultWidth: 25,
    defaultHeight: 25,
    description: "Nightstand",
    category: "Nightstand",
    type: "furniture",
  },
  {
    itemKey: 11,
    url: "vectors/furniture/squarebrownnightstand.PNG",
    defaultWidth: 30,
    defaultHeight: 20,
    description: "Nightstand",
    category: "Nightstand",
    type: "furniture",
  },
  {
    itemKey: 12,
    url: "vectors/furniture/squarewhitenightstand.PNG",
    defaultWidth: 30,
    defaultHeight: 20,
    description: "Nightstand",
    category: "Nightstand",
    type: "furniture",
  },
  {
    itemKey: 13,
    url: "vectors/furniture/cornershelves.PNG",
    defaultWidth: 24,
    defaultHeight: 24,
    description: "Corner Shelves",
    category: "Corner Shelves",
    type: "furniture",
  },
  {
    itemKey: 14,
    url: "vectors/furniture/cubbyshelf.PNG",
    defaultWidth: 36,
    defaultHeight: 20,
    description: "Cubby Shelf",
    category: "Cubby Shelf",
    type: "furniture",
  },
  {
    itemKey: 15,
    url: "vectors/furniture/floorshelves.PNG",
    defaultWidth: 36,
    defaultHeight: 18,
    description: "Floor Shelves",
    category: "Floor Shelves",
    type: "furniture",
  },
  {
    itemKey: 16,
    url: "vectors/furniture/largeblackshelves.PNG",
    defaultWidth: 60,
    defaultHeight: 20,
    description: "Large Black Shelves",
    category: "Large Black Shelves",
    type: "furniture",
  },
  {
    itemKey: 17,
    url: "vectors/furniture/largebrownshelves.PNG",
    defaultWidth: 60,
    defaultHeight: 20,
    description: "Large Brown Shelves",
    category: "Large Brown Shelves",
    type: "furniture",
  },
  {
    itemKey: 18,
    url: "vectors/furniture/mediumblackshelves.PNG",
    defaultWidth: 50,
    defaultHeight: 20,
    description: "Medium Black Shelves",
    category: "Medium Black Shelves",
    type: "furniture",
  },
  {
    itemKey: 19,
    url: "vectors/furniture/shelfwithpictures.PNG",
    defaultWidth: 60,
    defaultHeight: 20,
    description: "Decorated Shelf",
    category: "Decorated Shelf",
    type: "furniture",
  },
  {
    itemKey: 20,
    url: "vectors/furniture/wireshelves.PNG",
    defaultWidth: 36,
    defaultHeight: 20,
    description: "Wire Shelves",
    category: "Wire Shelves",
    type: "furniture",
  },
  {
    itemKey: 21,
    url: "vectors/furniture/browntvstand.PNG",
    defaultWidth: 60,
    defaultHeight: 18,
    description: "Brown TV Stand",
    category: "Brown TV Stand",
    type: "furniture",
  },
  {
    itemKey: 22,
    url: "vectors/furniture/greytvstand.PNG",
    defaultWidth: 50,
    defaultHeight: 18,
    description: "Grey TV Stand",
    category: "Grey TV Stand",
    type: "furniture",
  },
  {
    itemKey: 23,
    url: "vectors/furniture/smalltvstand.PNG",
    defaultWidth: 36,
    defaultHeight: 18,
    description: "Small TV Stand",
    category: "Small TV Stand",
    type: "furniture",
  },
  {
    itemKey: 24,
    url: "vectors/furniture/yellowtvstand.PNG",
    defaultWidth: 50,
    defaultHeight: 18,
    description: "Yellow TV Stand",
    category: "Small TV Stand",
    type: "furniture",
  },
  {
    itemKey: 25,
    url: "vectors/furniture/brownvanity.PNG",
    defaultWidth: 50,
    defaultHeight: 18,
    description: "Brown Vanity",
    category: "Brown Vanity",
    type: "furniture",
  },
  {
    itemKey: 26,
    url: "vectors/furniture/whitevanity.PNG",
    defaultWidth: 50,
    defaultHeight: 18,
    description: "White Vanity",
    category: "White Vanity",
    type: "furniture",
  },
  {
    itemKey: 27,
    url: "vectors/furniture/blackwardrobe.PNG",
    defaultWidth: 40,
    defaultHeight: 20,
    description: "Black Wardrobe",
    category: "Black Wardrobe",
    type: "furniture",
  },
  {
    itemKey: 28,
    url: "vectors/furniture/brownwardrobe.PNG",
    defaultWidth: 40,
    defaultHeight: 20,
    description: "Brown Wardrobe",
    category: "Brown Wardrobe",
    type: "furniture",
  },
  {
    itemKey: 29,
    url: "vectors/furniture/smallblackwardrobe.PNG",
    defaultWidth: 30,
    defaultHeight: 20,
    description: "Small Black Wardrobe",
    category: "Small Black Wardrobe",
    type: "furniture",
  },
  {
    itemKey: 30,
    url: "vectors/furniture/smallbrownwardrobe.PNG",
    defaultWidth: 30,
    defaultHeight: 20,
    description: "Small Brown Wardrobe",
    category: "Small Brown Wardrobe",
    type: "furniture",
  },
  {
    itemKey: 31,
    url: "vectors/furniture/blackchair.PNG",
    defaultWidth: 30,
    defaultHeight: 30,
    description: "Black Chair",
    category: "Black Chair",
    type: "furniture",
  },
  {
    itemKey: 32,
    url: "vectors/furniture/blackstool.PNG",
    defaultWidth: 25,
    defaultHeight: 25,
    description: "Black Stool",
    category: "Black Stool",
    type: "furniture",
  },
  {
    itemKey: 33,
    url: "vectors/furniture/paddedchair.PNG",
    defaultWidth: 30,
    defaultHeight: 30,
    description: "Padded Chair",
    category: "Padded Chair",
    type: "furniture",
  },
  {
    itemKey: 34,
    url: "vectors/furniture/whitechair.PNG",
    defaultWidth: 30,
    defaultHeight: 30,
    description: "White Chair",
    category: "White Chair",
    type: "furniture",
  },
  {
    itemKey: 35,
    url: "vectors/furniture/blackdesk.PNG",
    defaultWidth: 60,
    defaultHeight: 30,
    description: "Black Desk",
    category: "Black Desk",
    type: "furniture",
  },
  {
    itemKey: 36,
    url: "vectors/furniture/browndesk.PNG",
    defaultWidth: 60,
    defaultHeight: 30,
    description: "Brown Desk",
    category: "Brown Desk",
    type: "furniture",
  },
  {
    itemKey: 37,
    url: "vectors/furniture/officechair1.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Officechair 1",
    category: "Officechair 1",
    type: "furniture",
  },
  {
    itemKey: 38,
    url: "vectors/furniture/officechair2.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Officechair 2",
    category: "Officechair 2",
    type: "furniture",
  },
  {
    itemKey: 39,
    url: "vectors/furniture/officechair3.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Officechair 3",
    category: "Officechair 3",
    type: "furniture",
  },
  {
    itemKey: 40,
    url: "vectors/furniture/officechair4.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Officechair 4",
    category: "Officechair 4",
    type: "furniture",
  },
  {
    itemKey: 41,
    url: "vectors/furniture/officechair5.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Officechair 5",
    category: "Officechair 5",
    type: "furniture",
  },
  {
    itemKey: 42,
    url: "vectors/furniture/glasstable.PNG",
    defaultWidth: 50,
    defaultHeight: 25,
    description: "Glass Table",
    category: "Glass Table",
    type: "furniture",
  },
  {
    itemKey: 43,
    url: "vectors/furniture/ovaltable.PNG",
    defaultWidth: 60,
    defaultHeight: 30,
    description: "Oval Table",
    category: "Oval Table",
    type: "furniture",
  },
  {
    itemKey: 44,
    url: "vectors/furniture/roundtable.PNG",
    defaultWidth: 50,
    defaultHeight: 50,
    description: "Round Table",
    category: "Round Table",
    type: "furniture",
  },
  {
    itemKey: 45,
    url: "vectors/furniture/tablewithchairs.PNG",
    defaultWidth: 70,
    defaultHeight: 40,
    description: "Dining Table",
    category: "Dining Table",
    type: "furniture",
  },
  {
    itemKey: 46,
    url: "vectors/furniture/whitetable.PNG",
    defaultWidth: 50,
    defaultHeight: 30,
    description: "White Table",
    category: "White Table",
    type: "furniture",
  },
  {
    itemKey: 47,
    url: "vectors/furniture/greyarmchair.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Grey Armchair",
    category: "Grey Armchair",
    type: "furniture",
  },
  {
    itemKey: 48,
    url: "vectors/furniture/largebluearmchair.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Blue Armchair",
    category: "Blue Armchair",
    type: "furniture",
  },
  {
    itemKey: 49,
    url: "vectors/furniture/mediumgreyarmchair.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Rounded Grey Armchair",
    category: "Rounded Grey Armchair",
    type: "furniture",
  },
  {
    itemKey: 50,
    url: "vectors/furniture/roundarmchair.PNG",
    defaultWidth: 35,
    defaultHeight: 30,
    description: "Round Armchair",
    category: "Round Armchair",
    type: "furniture",
  },
  {
    itemKey: 51,
    url: "vectors/furniture/tallarmchair.PNG",
    defaultWidth: 40,
    defaultHeight: 35,
    description: "Tall Armchair",
    category: "Tall Armchair",
    type: "furniture",
  },
  {
    itemKey: 52,
    url: "vectors/furniture/greysquareottoman.PNG",
    defaultWidth: 35,
    defaultHeight: 20,
    description: "Grey Ottoman",
    category: "Grey Ottoman",
    type: "furniture",
  },
  {
    itemKey: 53,
    url: "vectors/furniture/leggedottoman.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Legged Ottoman",
    category: "Legged Ottoman",
    type: "furniture",
  },
  {
    itemKey: 54,
    url: "vectors/furniture/roundottoman.PNG",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Round Ottoman",
    category: "Round Ottoman",
    type: "furniture",
  },
  {
    itemKey: 55,
    url: "vectors/furniture/yellowsquareottoman.PNG",
    defaultWidth: 35,
    defaultHeight: 20,
    description: "Yellow Ottoman",
    category: "Yellow Ottoman",
    type: "furniture",
  },
  {
    itemKey: 56,
    url: "vectors/furniture/blacksofa.PNG",
    defaultWidth: 70,
    defaultHeight: 25,
    description: "Black Sofa",
    category: "Black Sofa",
    type: "furniture",
  },
  {
    itemKey: 57,
    url: "vectors/furniture/Green Sofa.PNG",
    defaultWidth: 70,
    defaultHeight: 25,
    description: "Green Sofa",
    category: "Green Sofa",
    type: "furniture",
  },
  {
    itemKey: 58,
    url: "vectors/furniture/Lsofa.PNG",
    defaultWidth: 110,
    defaultHeight: 50,
    description: "Corner Sofa",
    category: "Corner Sofa",
    type: "furniture",
  },
  {
    itemKey: 59,
    url: "vectors/furniture/reclinersofa.PNG",
    defaultWidth: 110,
    defaultHeight: 250,
    description: "Recliner Sofa",
    category: "Recliner Sofa",
    type: "furniture",
  },
  {
    itemKey: 60,
    url: "vectors/furniture/roundedsofa.PNG",
    defaultWidth: 70,
    defaultHeight: 25,
    description: "Rounded Sofa",
    category: "Rounded Sofa",
    type: "furniture",
  },
  {
    itemKey: 61,
    url: "vectors/furniture/Usofa.PNG",
    defaultWidth: 120,
    defaultHeight: 60,
    description: "U Sofa",
    category: "U Sofa",
    type: "furniture",
  },
  {
    itemKey: 11,
    url: "vectors/furniture/carpet.svg",
    defaultWidth: 60,
    defaultHeight: 100,
    description: "Carpet",
    category: "Carpet",
    type: "furniture",
  },
  {
    itemKey: 12,
    url: "vectors/furniture/rug.png",
    defaultWidth: 60,
    defaultHeight: 100,
    description: "Carpet 2",
    category: "Carpet 2",
    type: "furniture",
  },
  {
    itemKey: 13,
    url: "vectors/furniture/lamp.svg",
    defaultWidth: 32,
    defaultHeight: 32,
    description: "Lamp",
    category: "Lamp",
    type: "furniture",
  },
  {
    itemKey: 14,
    url: "vectors/furniture/minifridge.svg",
    defaultWidth: 25,
    defaultHeight: 25,
    description: "Fridge",
    category: "Fridge",
    type: "furniture",
  },
  {
    itemKey: 15,
    url: "vectors/furniture/plant.svg",
    defaultWidth: 32,
    defaultHeight: 32,
    description: "Plant",
    category: "Plant",
    type: "furniture",
  },
  {
    itemKey: 16,
    url: "vectors/furniture/leaf.svg",
    defaultWidth: 32,
    defaultHeight: 32,
    description: "Plant",
    category: "Plant",
    type: "furniture",
  },
  {
    itemKey: 17,
    url: "vectors/furniture/roundedsofa.png",
    defaultWidth: 110,
    defaultHeight: 25,
    description: "Sofa 1",
    category: "Sofa 1",
    type: "furniture",
  },
  {
    itemKey: 18,
    url: "vectors/furniture/squaresofa.png",
    defaultWidth: 110,
    defaultHeight: 25,
    description: "Sofa 2",
    category: "Sofa 2",
    type: "furniture",
  },
  {
    itemKey: 19,
    url: "vectors/furniture/cornercouch.svg",
    defaultWidth: 94,
    defaultHeight: 65,
    description: "Corner Couch",
    category: "Corner Couch",
    type: "furniture",
  },
  {
    itemKey: 20,
    url: "vectors/furniture/ottoman.png",
    defaultWidth: 25,
    defaultHeight: 15,
    description: "Ottoman",
    category: "Ottoman",
    type: "furniture",
  },
  {
    itemKey: 21,
    url: "vectors/furniture/tvstand.png",
    defaultWidth: 65,
    defaultHeight: 15,
    description: "TV Stand",
    category: "TV Stand",
    type: "furniture",
  },
  {
    itemKey: 22,
    url: "vectors/furniture/coffeetable.png",
    defaultWidth: 45,
    defaultHeight: 30,
    description: "Coffee Table",
    category: "Coffee Table",
    type: "furniture",
  },
  {
    itemKey: 23,
    url: "vectors/furniture/beanbag.svg",
    defaultWidth: 35,
    defaultHeight: 35,
    description: "Beanbag",
    category: "Beanbag",
    type: "furniture",
  },
  {
    itemKey: 24,
    url: "vectors/furniture/capybara.png",
    defaultWidth: 15,
    defaultHeight: 15,
    description: "Capybara",
    category: "Capybara",
    type: "furniture",
  },
  {
    itemKey: 25,
    url: "vectors/furniture/duck.png",
    defaultWidth: 15,
    defaultHeight: 15,
    description: "Duck",
    category: "Duck",
    type: "furniture",
  },
  
];

export default furnitureData;