const furnitureData = [
    {
      itemKey: 1,
      url: "vectors/furniture/doublepillowbed.png",
      defaultWidth: 60,
      defaultHeight: 80,
      description: "Queen Bed",
      category: "Bed",
      type: "furniture",
    },
    {
      itemKey: 2,
      url: "vectors/furniture/singlepillowbed.png",
      defaultWidth: 38,
      defaultHeight: 75,
      description: "Twin Bed",
      category: "Twin Bed",
      type: "furniture",
    },
    {
      itemKey: 3,
      url: "vectors/furniture/nightstand.png",
      defaultWidth: 20,
      defaultHeight: 15,
      description: "Nightstand",
      category: "Nightstand",
      type: "furniture",
    },
    {
      itemKey: 4,
      url: "vectors/furniture/2x2drawers.png",
      defaultWidth: 50,
      defaultHeight: 20,
      description: "Dresser",
      category: "Dresser",
      type: "furniture",
    },
    {
      itemKey: 5,
      url: "vectors/furniture/desk.png",
      defaultWidth: 50,
      defaultHeight: 36,
      description: "Desk",
      category: "Desk",
      type: "furniture",
    },
    {
      itemKey: 6,
      url: "vectors/furniture/hutchdesk.png",
      defaultWidth: 50,
      defaultHeight: 36,
      description: "Hutch Desk",
      category: "Hutch Desk",
      type: "furniture",
    },
    {
      itemKey: 7,
      url: "vectors/furniture/cornerdesk.svg",
      defaultWidth: 60,
      defaultHeight: 60,
      description: "Corner Desk",
      category: "Corner Desk",
      type: "furniture",
    },
    {
      itemKey: 8,
      url: "vectors/furniture/officechair.svg",
      defaultWidth: 30,
      defaultHeight: 30,
      description: "Desk Chair",
      category: "Chair",
      type: "furniture",
    },
    {
      itemKey: 9,
      url: "vectors/furniture/armchair.png",
      defaultWidth: 35,
      defaultHeight: 35,
      description: "Armchair 1",
      category: "Armchair 1",
      type: "furniture",
    },
    {
      itemKey: 10,
      url: "vectors/furniture/armchair.svg",
      defaultWidth: 35,
      defaultHeight: 35,
      description: "Armchair 2",
      category: "Armchair 2",
      type: "furniture",
    },
    {
      itemKey: 11,
      url: "vectors/furniture/carpet.svg",
      defaultWidth: 60,
      defaultHeight: 100,
      description: "Carpet",
      category: "Carpet",
      type: "furniture",
    },
    {
      itemKey: 12,
      url: "vectors/furniture/rug.png",
      defaultWidth: 60,
      defaultHeight: 100,
      description: "Carpet 2",
      category: "Carpet 2",
      type: "furniture",
    },
    {
      itemKey: 13,
      url: "vectors/furniture/lamp.svg",
      defaultWidth: 32,
      defaultHeight: 32,
      description: "Lamp",
      category: "Lamp",
      type: "furniture",
    },
    {
      itemKey: 14,
      url: "vectors/furniture/minifridge.svg",
      defaultWidth: 25,
      defaultHeight: 25,
      description: "Fridge",
      category: "Fridge",
      type: "furniture",
    },
    {
      itemKey: 15,
      url: "vectors/furniture/plant.svg",
      defaultWidth: 32,
      defaultHeight: 32,
      description: "Plant",
      category: "Plant",
      type: "furniture",
    },
    {
      itemKey: 16,
      url: "vectors/furniture/leaf.svg",
      defaultWidth: 32,
      defaultHeight: 32,
      description: "Plant",
      category: "Plant",
      type: "furniture",
    },
    {
      itemKey: 17,
      url: "vectors/furniture/roundedsofa.png",
      defaultWidth: 110,
      defaultHeight: 25,
      description: "Sofa 1",
      category: "Sofa 1",
      type: "furniture",
    },
    {
      itemKey: 18,
      url: "vectors/furniture/squaresofa.png",
      defaultWidth: 110,
      defaultHeight: 25,
      description: "Sofa 2",
      category: "Sofa 2",
      type: "furniture",
    },
    {
      itemKey: 19,
      url: "vectors/furniture/cornercouch.svg",
      defaultWidth: 94,
      defaultHeight: 65,
      description: "Corner Couch",
      category: "Corner Couch",
      type: "furniture",
    },
    {
      itemKey: 20,
      url: "vectors/furniture/ottoman.png",
      defaultWidth: 25,
      defaultHeight: 15,
      description: "Ottoman",
      category: "Ottoman",
      type: "furniture",
    },
    {
      itemKey: 21,
      url: "vectors/furniture/tvstand.png",
      defaultWidth: 65,
      defaultHeight: 15,
      description: "TV Stand",
      category: "TV Stand",
      type: "furniture",
    },
    {
      itemKey: 22,
      url: "vectors/furniture/coffeetable.png",
      defaultWidth: 45,
      defaultHeight: 30,
      description: "Coffee Table",
      category: "Coffee Table",
      type: "furniture",
    },
    {
      itemKey: 23,
      url: "vectors/furniture/beanbag.svg",
      defaultWidth: 35,
      defaultHeight: 35,
      description: "Beanbag",
      category: "Beanbag",
      type: "furniture",
    },
    {
      itemKey: 24,
      url: "vectors/furniture/capybara.png",
      defaultWidth: 15,
      defaultHeight: 15,
      description: "Capybara",
      category: "Capybara",
      type: "furniture",
    },
    {
      itemKey: 25,
      url: "vectors/furniture/duck.png",
      defaultWidth: 15,
      defaultHeight: 15,
      description: "Duck",
      category: "Duck",
      type: "furniture",
    },
    
  ];

export default furnitureData;