# Generated by Django 4.1.7 on 2023-04-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('fileID', models.CharField(default='', max_length=30)),
                ('modifiedDate', models.CharField(default='', max_length=150)),
                ('createDate', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
