# Generated by Django 4.1.7 on 2023-04-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designfile',
            name='fileID',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
